# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\ncalculator\"(\n\nAddRequest\x12\x0c\n\x04num1\x18\x01 \x01(\x05\x12\x0c\n\x04num2\x18\x02 \x01(\x05\"\x1d\n\x0b\x41\x64\x64Response\x12\x0e\n\x06result\x18\x01 \x01(\x05\",\n\x0e\x41\x64\x64MultRequest\x12\x0c\n\x04num1\x18\x01 \x01(\x05\x12\x0c\n\x04num2\x18\x02 \x01(\x05\"-\n\x0f\x41\x64\x64MultResponse\x12\x0c\n\x04num1\x18\x01 \x01(\x05\x12\x0c\n\x04num2\x18\x02 \x01(\x05\x32\x88\x01\n\nCalculator\x12\x36\n\x03\x41\x64\x64\x12\x16.calculator.AddRequest\x1a\x17.calculator.AddResponse\x12\x42\n\x07\x41\x64\x64Mult\x12\x1a.calculator.AddMultRequest\x1a\x1b.calculator.AddMultResponseb\x06proto3')



_ADDREQUEST = DESCRIPTOR.message_types_by_name['AddRequest']
_ADDRESPONSE = DESCRIPTOR.message_types_by_name['AddResponse']
_ADDMULTREQUEST = DESCRIPTOR.message_types_by_name['AddMultRequest']
_ADDMULTRESPONSE = DESCRIPTOR.message_types_by_name['AddMultResponse']
AddRequest = _reflection.GeneratedProtocolMessageType('AddRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDREQUEST,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:calculator.AddRequest)
  })
_sym_db.RegisterMessage(AddRequest)

AddResponse = _reflection.GeneratedProtocolMessageType('AddResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESPONSE,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:calculator.AddResponse)
  })
_sym_db.RegisterMessage(AddResponse)

AddMultRequest = _reflection.GeneratedProtocolMessageType('AddMultRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDMULTREQUEST,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:calculator.AddMultRequest)
  })
_sym_db.RegisterMessage(AddMultRequest)

AddMultResponse = _reflection.GeneratedProtocolMessageType('AddMultResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADDMULTRESPONSE,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:calculator.AddMultResponse)
  })
_sym_db.RegisterMessage(AddMultResponse)

_CALCULATOR = DESCRIPTOR.services_by_name['Calculator']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADDREQUEST._serialized_start=32
  _ADDREQUEST._serialized_end=72
  _ADDRESPONSE._serialized_start=74
  _ADDRESPONSE._serialized_end=103
  _ADDMULTREQUEST._serialized_start=105
  _ADDMULTREQUEST._serialized_end=149
  _ADDMULTRESPONSE._serialized_start=151
  _ADDMULTRESPONSE._serialized_end=196
  _CALCULATOR._serialized_start=199
  _CALCULATOR._serialized_end=335
# @@protoc_insertion_point(module_scope)
